# -*- coding: utf-8 -*-
"""my maths wizard game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yyzGb1Nv2xvIP1FqQoRFaZUAC8_1FQ9U
"""

import random
import time

aname = input("Enter your name: ")
print(f"{aname}, Ready to Start the Math WIZI Game?")
OPERATORS = ["+", "-", "*"]
MIN_OPERAND = 6
MAX_OPERAND = 20
TOTAL_PROBLEMS = 10


def generate_problem():
    left = random.randint(MIN_OPERAND, MAX_OPERAND)
    right = random.randint(MIN_OPERAND, MAX_OPERAND)
    operator = random.choice(OPERATORS)

    expr = str(left) + " " + operator + " " + str(right)
    answer = eval(expr)
    return expr, answer


wrong = 0
input("Press enter to start!")
print("----------------------")

start_time = time.time()

for i in range(TOTAL_PROBLEMS):
    expr, answer = generate_problem()
    while True:
        guess = input("Problem #" + str(i + 1) + ": " + expr + " = ")
        if guess == str(answer):
            break
        wrong += 1

end_time = time.time()
total_time = round(end_time - start_time, 2)

print("----------------------")
print(f"{aname}, Nice work! You finished in", total_time, "seconds!")