# -*- coding: utf-8 -*-
"""MY PYTHON ASSIGNMENT TODAY.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xzg3x81kP0RkADArbc7eZwh-kgm0UzHm
"""

currentyear = 2023
# defining the year with which i will use to calculate the ages of the students
a = input("Enter student 1 name: ")
b = input("Enter student 2 name: ")
c = input("Enter student 3 name: ")
d = input("Enter student 4 name: ")
p = "years old"
# defining the "years old" as "p" which i will later format into the code
student_names = [a,b,c,d]
for i in range(1, 5):
  # to delimit the propmpt display to 4 values and to repeat the prompt for the 4 students
    age = int(input(f"Enter birthyear of student {i}: "))
  #to make the code display the birthyear in interger and also repeat the question for the four students
    student_ages = currentyear - age
    # to calculate the ages of the students
    print(f"{student_names[i-1]} is {student_ages} {p}")
    #to allow the code to assign the names of the students as to scores and their ages
    # the f allows me to be able to insert the already defined p variable

def Hello():
  # to greet and welcome the user
  aname = input("Enter your name: ")
  # to store the name of the operator or user in a variable and tell him or her to input name
  print(f"{aname}, welcome to Stetson grade calculator")
#to call the name of the user back here as a joinder to the sentence, you have to use format function


def name():
  student1 = input("Enter the student name: ")
  #to tell the user to input the first student's name
  return student1
  #to recall the student


def calc(student1):
    r = float(input("Enter first exam score: "))
    # recognises that the exam score value might be in decimal, hence, the float and also tells the user to input the student's exam score
    s = float(input("Enter second exam score: "))
    t = float(input("Enter third exam score: "))
    sum = float(r + s + t)
    # a calculator function to add and get the total scores
    average_exam_score = sum / 3
    # a function to get the average scores of the 3 exam scores
    print(f"{student1}'s average score is {average_exam_score:.2f}")
    #to include the student's name to the sentence and tells the computer to print it out, while calculating the average scores and formatting it to 2 significant places incase there is a decimal or float value
    return average_exam_score

def calculate_letter_grades(student1, average_exam_score):
  #methods to allow me use variables from previous methods
    if average_exam_score >= 90 and average_exam_score <= 100:
      #conditions that define the range of scores and output
      print(f"{student1}'s grade is A")
    elif average_exam_score >= 80 and average_exam_score <= 89:
      print(f"{student1}'s grade is B")
    elif average_exam_score >= 70 and average_exam_score <= 79:
      print(f"{student1}'s grade is C")
    elif average_exam_score >= 60 and average_exam_score <= 69:
      print(f"{student1}'s grade is D")
    elif average_exam_score >= 50 and average_exam_score <= 59:
      print(f"{student1}'s grade is E")
    elif average_exam_score >= 1 and   average_exam_score <= 49:
      print(f"{student1}'s grade is F")
    else:
      print("Invalid input")





def goodbye():
  #to define the goodbye method
  print("Thank you for using this calculator")





Hello()
#to call back the hello method

for num in range(4):
  v = name()
  #to call the name method
  w = calc(v)
  #to call the calc method
  x = calculate_letter_grades(v, w)
  goodbye()
  #calling the goodbye function